### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by OriolAbril**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by OriolAbril** [comment]
pypi still needs to upload the tar to the location in the recipe. Will try again later

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Review by maresb — APPROVED** [review]

**Comment by maresb** [comment]
Looks good! BTW, no need to do this manually. It should happen automatically if you wait an hour or two, but you do need to check that the dependency pins are correct.

**Comment by OriolAbril** [comment]
yes, I opened the PR to fix the dependencies mostly which aren't automatic. Thanks for the help!

**Comment by maresb** [comment]
No problem! I just added some magic in 276a611 to enable the "Grayskull" tool to attempt to automatically update those dependencies. (It doesn't work on multi-output feedstocks like PyMC though.) It still needs to be checked though.

**Comment by OriolAbril** [comment]
it's an issue with the pydata-sphinx-theme recipe, I'll send a PR: https://github.com/conda-forge/pydata-sphinx-theme-feedstock/pull/45

**Comment by OriolAbril** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
